# Generated by Django 6.0.5 on 2026-06-10 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_event_ids(apps, schema_editor):
    Payment = apps.get_model('payments', 'Payment')
    Event = apps.get_model('events', 'Event')
    for payment in Payment.objects.all():
        if payment.legacy_event_id:
            try:
                event = Event.objects.get(id=payment.legacy_event_id)
                payment.event = event
                payment.save()
            except Event.DoesNotExist:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_events_even_status_ac44c5_idx_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='event_id',
            new_name='legacy_event_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='events.event'),
        ),
        migrations.RunPython(copy_event_ids, reverse_code=migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
    ]
