# Generated by Django 6.0.5 on 2026-06-10 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_event_id_payment_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='legacy_event_id',
        ),
    ]
