# Generated by Django 5.1.3 on 2026-06-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_paymentorder_stk_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendeenotification',
            new_name='payments_at_attende_cf0285_idx',
            old_name='payments_at_attende_2d3e4f_idx',
        ),
        migrations.RenameIndex(
            model_name='organizernotification',
            new_name='payments_or_organiz_0a80e7_idx',
            old_name='payments_or_organiz_9a0b1c_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentorder',
            new_name='payments_pa_status_75a59b_idx',
            old_name='payments_pa_status_8a1f2c_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentorder',
            new_name='payments_pa_attende_0972ab_idx',
            old_name='payments_pa_attende_3b4c5d_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentorder',
            new_name='payments_pa_organiz_d6403a_idx',
            old_name='payments_pa_organiz_6e7f8a_idx',
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='screenshot_data',
            field=models.TextField(blank=True, help_text='Base64 data-URI screenshot (used on serverless where media/ is read-only).'),
        ),
    ]
