# Generated by Django 6.0.5 on 2026-06-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendee_reviews_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_summary_sent',
            field=models.BooleanField(default=False),
        ),
    ]
