# Generated by Django 6.0.5 on 2026-06-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_attendee_reviews_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('sold_out', 'Sold Out')], default='draft', max_length=20),
        ),
    ]
