# Generated by Django 6.0.5 on 2026-06-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner_image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.TextField(),
        ),
    ]
