# Generated by Django 6.0.5 on 2026-06-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_banner_image_alter_eventimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='vip_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='vvip_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
