# Generated by Django 6.0.5 on 2026-06-10 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_vip_price_event_vvip_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'end_date'], name='events_even_status_ac44c5_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'start_date'], name='events_even_status_dfba18_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_featured', 'status'], name='events_even_is_feat_ff8c54_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['price'], name='events_even_price_ab7caf_idx'),
        ),
    ]
