# Generated by Django 6.0.5 on 2026-06-10 13:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def migrate_json_to_tables(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    TeamMember = apps.get_model('accounts', 'TeamMember')
    ApiKey = apps.get_model('accounts', 'ApiKey')
    
    for user in User.objects.all():
        # Migrate team members JSON to TeamMember model
        if hasattr(user, 'team_members') and user.team_members:
            for member in user.team_members:
                member_id = member.get('id')
                email = member.get('email')
                role = member.get('role', 'viewer')
                if member_id and email:
                    TeamMember.objects.get_or_create(
                        id=member_id,
                        defaults={
                            'organizer': user,
                            'email': email,
                            'role': role
                        }
                    )
                    
        # Migrate API keys JSON to ApiKey model
        if hasattr(user, 'api_keys') and user.api_keys:
            for key_data in user.api_keys:
                key_id = key_data.get('id')
                name = key_data.get('name', 'Developer Key')
                key_val = key_data.get('key')
                created_at_str = key_data.get('created_at')
                
                from django.utils.dateparse import parse_datetime
                created_at = None
                if created_at_str:
                    created_at = parse_datetime(created_at_str)
                
                if not created_at:
                    from django.utils import timezone
                    created_at = timezone.now()
                    
                if key_id and key_val:
                    ApiKey.objects.get_or_create(
                        id=key_id,
                        defaults={
                            'organizer': user,
                            'name': name,
                            'key': key_val,
                            'created_at': created_at
                        }
                    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_google_id'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(default='viewer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='accounts_us_role_1fa9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='accounts_us_role_2b136f_idx'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys_rel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammember',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members_rel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['organizer'], name='accounts_ap_organiz_b0f2ae_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key'], name='accounts_ap_key_d955e0_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['organizer'], name='accounts_te_organiz_94bf34_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['email'], name='accounts_te_email_cefc4d_idx'),
        ),
        migrations.RunPython(migrate_json_to_tables, reverse_code=migrations.RunPython.noop),
    ]
