# Generated by Django 6.0.5 on 2026-06-10 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_apikey_teammember_user_accounts_us_role_1fa9a5_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='api_keys',
        ),
        migrations.RemoveField(
            model_name='user',
            name='team_members',
        ),
    ]
