# Generated by Django 5.1.3 on 2026-06-12 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_teammember_unique_organizer_email'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminnotificationstate',
            new_name='accounts_ad_is_dism_250a16_idx',
            old_name='accounts_ad_is_dism_0c0f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='adminnotificationstate',
            new_name='accounts_ad_is_read_32b1f6_idx',
            old_name='accounts_ad_is_read_8f2a1b_idx',
        ),
    ]
