# Generated by Django 6.0.5 on 2026-06-10 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('events', '0007_event_events_even_status_ac44c5_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='bookings_ti_status_90f1ac_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['purchase_date'], name='bookings_ti_purchas_429890_idx'),
        ),
    ]
